### ISSUE TITLE
Token expires in the middle of the uploads

### ISSUE THREAD

**Issue by zufanka** [resolve-works/insight#118]

**Comment by monneyboi** [comment]
Reproduced here, `requests-oauthlib`. Requests are also not retried when token expired.

```
ERROR:root:permission denied for view inodes

```

**Comment by monneyboi** [comment]
This was caused by `keyring` returning `None` randomly. Presumably because it doesn't like to be called x times per second. 

Solution is to create a client instance once.

**Comment by monneyboi** [comment]
InsightClient extends oauth session now to make use of the loaded tokens to prevent calling the keyring to often. Keyring is also back.
